name: Auto build DispatchTool from scheme.txt

on:
  push:
    branches: [ "main" ]
    paths:
      - "data/scheme.txt"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build DispatchTool.html
        run: |
          node tools/build.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add DispatchTool.html
          if ! git diff --cached --quiet; then
            git commit -m "Auto build DispatchTool from scheme.txt update"
            git push
          else
            echo "No changes in DispatchTool.html"
          fi
